# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0002_auto_20170222_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_daily_traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=100)),
                ('traffic', models.FloatField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriesId', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('total_rmb', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City_trading_volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_rmb', models.FloatField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('categoriesId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity_subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_rmb', models.FloatField()),
                ('Commodity_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Commodity_categories')),
            ],
        ),
        migrations.CreateModel(
            name='provinces_rmb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rmb', models.FloatField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='real',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmb', models.FloatField()),
                ('numner', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='source_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
                ('number', models.FloatField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rmb', models.FloatField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('categoriesId', models.IntegerField(null=True)),
                ('categoriesName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='The_number_of_clicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
                ('number', models.FloatField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
